# ************************************************************************
# Product    : Home information and control
# Date       : 2016-12-21
# Copyright  : Copyright (C) 2016 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : mqtt-manager/Dockerfile-rpi
# Version    : 0.3.1
# Author     : Bjorn Kjeholt
# *************************************************************************
 
FROM bkjeholt/base-nodejs:latest-rpi

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

RUN apk update && \
    apk add mysql-client

ARG DOCKER_IMAGE_NAME
ARG DOCKER_IMAGE_TAG

ENV DOCKER_IMAGE_NAME ${DOCKER_IMAGE_NAME:-UnknownName}
ENV DOCKER_IMAGE_TAG ${DOCKER_IMAGE_TAG:-UnknownRevision}

